export const Types = {
	App: Symbol.for('App'),
	UsersController: Symbol.for('UsersController'),
	EnvService: Symbol.for('EnvService'),
	LoggerService: Symbol.for('LoggerService'),
	ErrorFilter: Symbol.for('ErrorFilter'),
	DbService: Symbol.for('DbService'),
	UserModel: Symbol.for('UserModel'),
	UsersRegistry: Symbol.for('UsersRegistry'),
	UsersService: Symbol.for('UsersService'),
	AuthMiddleware: Symbol.for('AuthMiddleware'),
	ImagesController: Symbol.for('ImagesController'),
	ImagesService: Symbol.for('ImagesService'),
	MessageModel: Symbol.for('MessageModel'),
	MessageRegistry: Symbol.for('MessageRegistry'),
	AuthController: Symbol.for('AuthController'),
	AuthService: Symbol.for('AuthService'),
	MessagesController: Symbol.for('Messages.Controller'),
	MessagesService: Symbol.for('MessagesService'),
};
